# Generated by Django 2.1 on 2019-08-30 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('lat', models.FloatField(default=12.9184)),
                ('lng', models.FloatField(default=79.1325)),
                ('phno', models.IntegerField(default='0')),
                ('cctvcode', models.CharField(default=0, max_length=10)),
                ('photage', models.ImageField(default='default.jpg', upload_to='cctv')),
                ('carsp', models.IntegerField(default=0)),
                ('choice', models.CharField(default=0, max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(default=0, max_length=10)),
                ('no_of_hours', models.IntegerField(default=0)),
            ],
        ),
    ]
