# Generated by Django 2.1 on 2019-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=12.9058),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=79.1371),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photage',
            field=models.ImageField(default='default.png', upload_to='cctv'),
        ),
    ]
