# Generated by Django 2.1 on 2019-10-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190914_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cost',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=12.9184),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.FloatField(default=79.1325),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photage',
            field=models.ImageField(default='qa.png', upload_to='cctv'),
        ),
    ]
