# Generated by Django 2.1 on 2019-07-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190722_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photage',
            field=models.ImageField(default='default.jpg', upload_to='cctv'),
        ),
    ]
